export const environment = {
  production: true,
  SANDBOX_APP_ID: 'sandbox-sq0idb-oIuWkzoUJ8mEoRWbd1N2BA',
  SANDBOX_TOKEN:
    'EAAAEGzB5TTlyZDdz3M45E-cYAW6FGuLyDN-VOUKcNzY57TIgvxGn2kqBlN4mu6-',
  SANDBOX_LOCATION: 'LCH842Y98K67A',
  PRODUCTION_APP_ID: 'sq0idp-WLFkNW2n8m0fxTesMjHxYw',
  PRODUCTION_TOKEN:
    'EAAAECBpOiUTyUy_xjrmrxVD4ni-_CLgkao-swvtX6Zij1R13sn-J1OoLTTZDilO',
  PRODUCTION_LOCATION: 'LNZTG918K38R9',
};
